### ISSUE TITLE
工作不到一年的前端开发，可以应聘贵公司的前端开发吗？ 

### ISSUE THREAD

**Issue by liuyidi** [guanghetv/guanghetv.github.io#2]
对于初级开发，需要哪些条件？

**Comment by stevennuo** [comment]
https://trello.com/b/0mEQexYD/- 

如果上面的链接还不够回答你，请继续骚扰我 ：）

**Comment by liuyidi** [comment]
@stevennuo 是通过这个链接找到贵司的githhub，上面写的都是实习和2，3年以上工作经验的，对于刚工作的好像比较尴尬，大致了解贵司的主要架构MEAN, 工具git/github,webstorm/sublime都是我的最爱，所以特别想了解下 需要达到哪个地步可以加入贵司？

**Comment by stevennuo** [comment]
目前我们暂时不招收初级工作者，如果你真的对我们感兴趣，建议你自学一段时间，过来面试，确定后可以直接用github联系我。

在 2015年10月9日 上午12:14，liuyidi notifications@github.com写道：
